Pipeline build implementation
Kynetics/uf-android-client pull request #18
Opened 2022-07-14 08:37 UTC by albertob13

Pipeline build first implementation with app signing management.

2022-07-18 09:48 UTC, diegorondini requested changes

2022-07-18 09:48 UTC, diegorondini commented on .github/workflows/pipeline-build.yml
> +name: build-action
Leave the pipeline stuff as a separate PR (just leave this one open, we'll eventually rebase).
We first need to merge the keys refactoring. Please open a dedicated PR for keys refactoring with the changes requested here.

2022-07-18 09:48 UTC, diegorondini commented on .github/workflows/pipeline-build.yml
> +          ALIAS_KEY_KYNETICS: ${{ secrets.ALIAS_KYNEICS_KEY }}
Typo in var name `KYNEICS`.

2022-07-18 09:48 UTC, diegorondini commented on .github/workflows/pipeline-build.yml
> +          PASS_KEYSTORE_KYNETICS: ${{ secrets.PASS_KEYSTORE_KYNETICS }}
Please use English language order for variables naming. If we're talking about the Kynetics keystore password, the variable should be named `KYNETICS_KEYSTORE_PASS`.

2022-07-18 09:48 UTC, diegorondini commented on keystore/buildkeystore.sh
> +#Delete current 'public.jks' and make sure ./keystore/ is free of subdirectories before run it.
> free of subdirectories before run it

This is not true. The `keystore/` folder should include the subfolders with the `.pk8` and `x509.pem` key pairs.

2022-07-18 09:48 UTC, diegorondini commented on keystore/buildkeystore.sh
> +	rm -f ./$(basename $d)_decrypted_key.p12
The `.p12` is not "decrypted". It's just a different (combined) format to store the keys:
https://support.ksoftware.net/support/solutions/articles/17251-what-is-a-p12-file-or-a-pkcs12-file-

2022-07-18 09:48 UTC, diegorondini commented on keystore/buildkeystore.sh
> +if [ $? -eq 0 ];
This `if` will always be true as you're just checking the return value of the previous command, which in this case is `echo ""`.

2022-07-18 09:48 UTC, diegorondini commented on uf-client-ui-example/build.gradle
> +    def passKeyStoreKynetics = System.getenv("PASS_KEYSTORE_KYNETICS")
See the other comment about English language order. This should have been: `def KyneticsKeystorePass = System.getenv("KYNETICS_KEYSTORE_PASS")`

2022-07-18 09:48 UTC, diegorondini commented on uf-client-ui-example/build.gradle
> +    def passKeyKynetics = System.getenv("PASS_KEY_KYNETICS")
Same as above

2022-07-18 14:45 UTC, albertob13 commented on keystore/buildkeystore.sh
> +#Delete current 'public.jks' and make sure ./keystore/ is free of subdirectories before run it.
I meant that any other subfolders not containing the necessary keys will not make the script work properly.

2022-07-20 08:30 UTC, diegorondini requested changes

2022-07-22 08:08 UTC, danielesergio approved these changes

2022-07-22 08:56 UTC, merged