Remove uf-client-ui-example from the repository
Kynetics/uf-android-client pull request #25
Opened 2023-04-27 10:40 UTC by SaeedRe

The UI Example is now named "Android Service API Reference Implementation"
and has been moved to the following repository:
https://github.com/Kynetics/uf-service-api-reference-implementation
Removed the UI example by:
- removing the corresponding code in uf-client-ui-example
- removing the UI example from README.md
- removing the private keystore used by the UI example

2023-05-02 15:31 UTC, diegorondini requested changes
The removal is ok for me.

We have tweaked the naming of the "UI Example" which is now "Android Service API Reference Implementation" and available at the repo https://github.com/Kynetics/uf-service-api-reference-implementation

So I would update the commit message to be:
```
Remove uf-client-ui-example from the repository

The UI Example is now named "Android Service API Reference Implementation"
and has been moved to the following repository:
https://github.com/Kynetics/uf-service-api-reference-implementation
Removed the UI example by:
- removing the corresponding code in uf-client-ui-example
- removing the UI example from README.md
- removing the private keystore used by the UI example
```

2023-05-02 16:01 UTC, danielesergio approved these changes

2023-05-04 07:12 UTC, SaeedRe commented
The requested changes has been applied.

2023-05-04 07:37 UTC, diegorondini approved these changes

2023-05-04 07:38 UTC, merged