Add check for rebooting after OTA update
Kynetics/uf-android-client pull request #30
Opened 2023-07-10 10:28 UTC by SaeedRe

There seems to be an issue that, when the service is crashed during the OTA update (Just when the update is finished), the update engine completes the update but the service is not aware of that, hence the device does not reboot, and the service reports that the device is rebooted on the same partition.

This commit adds a check, if the device is not rebooted during the update, it will reboot the device.

2023-07-13 09:27 UTC, danielesergio requested changes
Refactor the install method in ABOtaInstaller class to be more readable.
Use a single when statement for all the cases.
here the pseudocode:
```
return when{
	* pending update && device rebooted ->;
	* pending update ->;
	* malformed ota -> { 
		for this case you need the payloadEntry and propEntry local variables, replace them with the 
                isOtaMalformed lazy boolean property (-> https://kotlinlang.org/docs/delegated-properties.html#lazy-properties 
	}
	* else -> ; // start a new installation
} 
```

Avoid using nested if-else when it is possible in favour of if-else, in kotlin use the when statement

2023-07-13 10:20 UTC, SaeedRe commented
Changes are made.

2023-07-20 10:07 UTC, danielesergio approved these changes

2023-07-27 11:41 UTC, diegorondini approved these changes

2023-07-27 11:42 UTC, merged