Force use dedicated url for ddi-client
Kynetics/uf-android-client pull request #40
Opened 2024-03-21 08:14 UTC by SaeedRe

Following the modifications to the OkHttp request behaviors
 in commit 3357972, to differentiate requests between the old and new
 service, the server URL of the ddi-client is adjusted to include the
 "ddi" subdomain.
It is recommended to utilize the new ddi URLs in the format "ddi.<tier>.updatefactory.io" for the service configuration.

2024-04-26 14:39 UTC, diegorondini requested changes
Please fix the typos and also add a test for external URLs like the hawkBit sandbox:
https://hawkbit.eclipseprojects.io

External URLs should never be modified.

2024-04-26 14:39 UTC, diegorondini commented on uf-client-service/src/androidTest/java/com/kynetics/uf/android/configuration/ConfigurationHandlerTest.kt
> +        val serverUrl = "https://ddi.bussiness.updatefactory.io"
```suggestion
        val serverUrl = "https://ddi.business.updatefactory.io"
```

2024-04-26 14:39 UTC, diegorondini commented on uf-client-service/src/androidTest/java/com/kynetics/uf/android/configuration/ConfigurationHandlerTest.kt
> +        val serverUrl = "https://cdn.bussiness.updatefactory.io"
```suggestion
        val serverUrl = "https://cdn.business.updatefactory.io"
```

2024-04-29 07:29 UTC, SaeedRe commented on uf-client-service/src/androidTest/java/com/kynetics/uf/android/configuration/ConfigurationHandlerTest.kt
> +        val serverUrl = "https://ddi.bussiness.updatefactory.io"
Changes are implemented.

2024-05-07 12:55 UTC, andrea-zoleo commented on uf-client-service/src/main/kotlin/com/kynetics/uf/android/configuration/ConfigurationHandler.kt
> +                val regex = """^\w+\.updatefactory\.io${'$'}""".toRegex()
Currently we use two different environment tagging. 
One for the "architectural" resources, as the AWS EKS clusters and so no, whose values currently are 'prod' and 'test', but in the future may be additional ones, and one for the "applicative" resources, as the K8S deployments and so on, whose values currently are 'stage', 'personal' and 'business'. 

In the canonical form of our URLs we use both these tags, for example 'stage.test.updatefactoy.io'. In the case of the 'prod' architectural tag, however, we support also the shortcut without 'prod'. For example ui.personal.prod.updatefactory.io --->  ui.personal.updatefactory.io.

For these reasons I suggest to change te regex to:
`"""^\w+\.([a-z0-9_]{3,10})?updatefactory\.io${'$'}""".toRegex()`

I also suggest to check that the host doesn't already start with `ddi.`

2024-05-07 13:28 UTC, SaeedRe commented on uf-client-service/src/main/kotlin/com/kynetics/uf/android/configuration/ConfigurationHandler.kt
> +                val regex = """^\w+\.updatefactory\.io${'$'}""".toRegex()
The Hara-DDI-Client employs the HTTP client to download artifacts from the cloud front using the "cdn" endpoint. The suggested regex will add the "ddi." prefix to a URL lacking the architectural infix. For instance, "cdn.stage.updatefactory.io" will become "ddi.cdn.stage.updatefactory.io".

However, since this fix only targets replacing deprecated URLs that might still be in use by customers, it can ensures that only existing architectural and applicative resources undergo URL changes. For any new environment or architecture, customers are encouraged to use the appropriate endpoints.

In this case the regex pattern would be:
`^(stage|personal|business)\.((prod|test)\.)?updatefactory\.io$`

2024-05-07 13:30 UTC, SaeedRe commented
Applied the new changes and also added more tests.

2024-05-07 13:53 UTC, diegorondini approved these changes

2024-05-07 13:55 UTC, merged