Fix update failure when rebooting during installation
Kynetics/uf-android-client pull request #41
Opened 2024-05-07 14:00 UTC by SaeedRe

This commit resolves the issue where the update action on the UF Server
 would become stuck in the updating state if the device rebooted during
 the update installation process, preventing the deployment of the same
 artifact file to the target again.
More information: UF-849

This fix is already tested and applied in v1.5.2

2024-05-07 14:07 UTC, andrea-zoleo approved these changes

2024-05-09 10:39 UTC, diegorondini requested changes

2024-05-09 10:39 UTC, diegorondini commented on uf-client-service/src/main/kotlin/com/kynetics/uf/android/update/CurrentUpdateState.kt
> +            Global.getInt(context.contentResolver, Global.BOOT_COUNT, 0)
I'd rather use getInt without the default:
https://developer.android.com/reference/android/provider/Settings.Global#getInt(android.content.ContentResolver,%20java.lang.String)

If there are occurrences where `Global.BOOT_COUNT` does not provide a value, then it's likely it'll not have a value at the next boot as well. In this case, you'll get the same `0` default value, making the two boots undistinguishable.

I'd rather get an exception and:

1. log the exception
2. use some other value (e.g. `-<pid-value` https://stackoverflow.com/a/25963694)

2024-05-09 10:39 UTC, diegorondini commented on uf-client-service/src/main/kotlin/com/kynetics/uf/android/update/CurrentUpdateState.kt
> +            0
If we need to have a magic value, then at least let's define a constant.

2024-05-14 11:53 UTC, diegorondini approved these changes

2024-05-14 12:16 UTC, merged